# Generated by Django 2.0.1 on 2018-09-20 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=20)),
                ('api_function', models.CharField(max_length=50)),
                ('api_path', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('validate', models.TextField(blank=True, null=True)),
                ('is_encry', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=20)),
                ('skip', models.CharField(blank=True, max_length=10, null=True)),
                ('skipIf', models.CharField(blank=True, max_length=50, null=True)),
                ('skipUnless', models.CharField(blank=True, max_length=50, null=True)),
                ('times', models.IntegerField(default=1)),
                ('variables', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('headers', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('body', models.TextField(blank=True, null=True)),
                ('extract', models.TextField(blank=True, null=True)),
                ('validate', models.TextField(blank=True, null=True)),
                ('setup_hooks', models.TextField(blank=True, default='[ ]', null=True)),
                ('teardown_hooks', models.TextField(blank=True, default='[ ]', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('encry_id', models.AutoField(primary_key=True, serialize=False)),
                ('encry_name', models.CharField(max_length=20)),
                ('encry_function', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='testCases',
            fields=[
                ('testCases_id', models.AutoField(primary_key=True, serialize=False)),
                ('testCases_name', models.CharField(max_length=20)),
                ('testSuite_function', models.CharField(blank=True, max_length=50, null=True)),
                ('parameters', models.TextField(blank=True, default='[ ]', null=True)),
                ('variables', models.TextField(blank=True, default='[ ]', null=True)),
                ('base_url_ip', models.CharField(max_length=30)),
                ('base_url_port', models.CharField(max_length=10)),
                ('headers', models.TextField(blank=True, null=True)),
                ('setup_hooks', models.TextField(blank=True, default='[ ]', null=True)),
                ('teardown_hooks', models.TextField(blank=True, default='[ ]', null=True)),
                ('testCases_list', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='testCases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.testCases'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.Project'),
        ),
        migrations.AddField(
            model_name='api',
            name='encryption_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.Encryption'),
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.Project'),
        ),
    ]
