# Generated by Django 2.0.1 on 2018-10-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0002_auto_20180926_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='is_encry',
            new_name='encry_flag',
        ),
    ]
