# Generated by Django 2.0.1 on 2018-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0003_auto_20181008_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='encry_function',
            field=models.CharField(max_length=200),
        ),
    ]
