# Generated by Django 2.0.1 on 2018-10-16 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0004_auto_20181010_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='testStep',
            fields=[
                ('testStep_id', models.AutoField(primary_key=True, serialize=False)),
                ('testStep_name', models.CharField(max_length=20)),
                ('skip', models.CharField(blank=True, max_length=10, null=True)),
                ('skipIf', models.CharField(blank=True, max_length=50, null=True)),
                ('skipUnless', models.CharField(blank=True, max_length=50, null=True)),
                ('times', models.IntegerField(default=1)),
                ('variables', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('headers', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('body', models.TextField(blank=True, null=True)),
                ('extract', models.TextField(blank=True, null=True)),
                ('validate', models.TextField(blank=True, null=True)),
                ('setup_hooks', models.TextField(blank=True, default='[ ]', null=True)),
                ('teardown_hooks', models.TextField(blank=True, default='[ ]', null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.Api')),
            ],
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.AddField(
            model_name='testcases',
            name='output',
            field=models.TextField(blank=True, default='[ ]', null=True),
        ),
    ]
