# Generated by Django 2.0.1 on 2018-10-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0008_auto_20181016_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teststep',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='testCases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.TestCases'),
        ),
    ]
