# Generated by Django 2.0.1 on 2018-10-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0010_auto_20181017_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='api_function',
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='testCases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.TestCases'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
