# Generated by Django 2.0.1 on 2018-11-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0011_auto_20181017_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='base_url_ip',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='base_url_port',
        ),
        migrations.AlterField(
            model_name='report',
            name='testCases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.TestCases'),
        ),
    ]
