# Generated by Django 2.0.1 on 2018-11-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0012_auto_20181106_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='testCases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.TestCases'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='output',
            field=models.CharField(blank=True, default='[]', max_length=150, null=True),
        ),
    ]
