# Generated by Django 2.0.1 on 2018-11-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0014_auto_20181108_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='body_type',
            new_name='body_data_type',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='headers_type',
            new_name='headers_data_type',
        ),
        migrations.RenameField(
            model_name='teststep',
            old_name='body_type',
            new_name='body_data_type',
        ),
        migrations.RenameField(
            model_name='teststep',
            old_name='headers_type',
            new_name='headers_data_type',
        ),
        migrations.AlterField(
            model_name='report',
            name='testCases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.TestCases'),
        ),
    ]
