# Generated by Django 2.0.1 on 2018-11-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0015_auto_20181108_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='autoTest.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='testCases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoTest.TestCases'),
        ),
    ]
