# Generated by Django 2.0.1 on 2018-11-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0016_auto_20181117_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='body_data_type',
        ),
        migrations.RemoveField(
            model_name='api',
            name='body_description',
        ),
        migrations.RemoveField(
            model_name='api',
            name='body_necessary_flag',
        ),
        migrations.RemoveField(
            model_name='api',
            name='encryption_type',
        ),
        migrations.RemoveField(
            model_name='api',
            name='headers_data_type',
        ),
        migrations.RemoveField(
            model_name='api',
            name='headers_description',
        ),
        migrations.RemoveField(
            model_name='api',
            name='headers_necessary_flag',
        ),
        migrations.RemoveField(
            model_name='api',
            name='project',
        ),
        migrations.RemoveField(
            model_name='api',
            name='validate_description',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='testCases',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='api',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='body_data_type',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='body_description',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='body_necessary_flag',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='headers_data_type',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='headers_description',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='headers_necessary_flag',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='project',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='validate_description',
        ),
        migrations.RemoveField(
            model_name='teststep',
            name='variables_description',
        ),
        migrations.AddField(
            model_name='api',
            name='dataType_list',
            field=models.TextField(blank=True, default='{"header":[], "body":[]}', null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='description_list',
            field=models.TextField(blank=True, default='{"header":[], "body":[], "validate":[]}', null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='necessaryFlag_list',
            field=models.TextField(blank=True, default='{"header":[], "body":[]}', null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='relative_enc',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='relative_pro',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environment',
            name='relative_pro',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='relative_testCases',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststep',
            name='dataType_list',
            field=models.TextField(blank=True, default='{"header":[], "body":[]}', null=True),
        ),
        migrations.AddField(
            model_name='teststep',
            name='description_list',
            field=models.TextField(blank=True, default='{"header":[], "body":[], "validate":[], "variables":[]}', null=True),
        ),
        migrations.AddField(
            model_name='teststep',
            name='necessaryFlag_list',
            field=models.TextField(blank=True, default='{"header":[], "body":[]}', null=True),
        ),
        migrations.AddField(
            model_name='teststep',
            name='relative_api',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststep',
            name='relative_pro',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
