# Generated by Django 2.0.1 on 2018-11-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0017_auto_20181119_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='dataType_list',
            new_name='dataType_dict',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='description_list',
            new_name='description_dict',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='necessaryFlag_list',
            new_name='necessaryFlag_dict',
        ),
        migrations.RenameField(
            model_name='teststep',
            old_name='dataType_list',
            new_name='dataType_dict',
        ),
        migrations.RenameField(
            model_name='teststep',
            old_name='description_list',
            new_name='description_dict',
        ),
        migrations.RenameField(
            model_name='teststep',
            old_name='necessaryFlag_list',
            new_name='necessaryFlag_dict',
        ),
    ]
