# Generated by Django 2.0.1 on 2018-12-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0018_auto_20181119_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='content_type',
            field=models.CharField(default='json', max_length=50),
            preserve_default=False,
        ),
    ]
