# Generated by Django 2.0.1 on 2018-12-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0019_teststep_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='dataType_dict',
            field=models.TextField(blank=True, default='{"header":[], "body":[], "validate":[]}', null=True),
        ),
        migrations.AddField(
            model_name='testcases',
            name='description_dict',
            field=models.TextField(blank=True, default='{"header":[], "body":[], "validate":[], "variables":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='dataType_dict',
            field=models.TextField(blank=True, default='{"header":[], "body":[], "validate":[]}', null=True),
        ),
    ]
