# Generated by Django 2.0.1 on 2018-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0020_auto_20181211_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='dataType_dict',
            field=models.TextField(blank=True, default='{"header":[], "parameters":[], "variables":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='description_dict',
            field=models.TextField(blank=True, default='{"header":[], "parameters":[], "variables":[]}', null=True),
        ),
    ]
