# Generated by Django 2.0.1 on 2018-12-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0021_auto_20181211_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='body',
            field=models.TextField(blank=True, default='{ }'),
        ),
        migrations.AlterField(
            model_name='api',
            name='dataType_dict',
            field=models.TextField(blank=True, default='{"headers":[], "body":[], "validate":[]}'),
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='api',
            name='description_dict',
            field=models.TextField(blank=True, default='{"headers":[], "body":[], "validate":[]}'),
        ),
        migrations.AlterField(
            model_name='api',
            name='headers',
            field=models.TextField(blank=True, default='{ }'),
        ),
        migrations.AlterField(
            model_name='api',
            name='necessaryFlag_dict',
            field=models.TextField(blank=True, default='{"headers":[], "body":[]}'),
        ),
        migrations.AlterField(
            model_name='api',
            name='validate',
            field=models.TextField(blank=True, default='[ ]'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='dataType_dict',
            field=models.TextField(blank=True, default='{"headers":[], "parameters":[], "variables":[]}'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='description_dict',
            field=models.TextField(blank=True, default='{"headers":[], "parameters":[], "variables":[]}'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='headers',
            field=models.TextField(blank=True, default='{ }'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='output',
            field=models.CharField(blank=True, default='[]', max_length=150),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='parameters',
            field=models.TextField(blank=True, default='[ ]'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='setup_hooks',
            field=models.CharField(blank=True, default='[]', max_length=200),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='teardown_hooks',
            field=models.CharField(blank=True, default='[]', max_length=200),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='testSuite_function',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='variables',
            field=models.TextField(blank=True, default='[ ]'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='body',
            field=models.TextField(blank=True, default='{ }'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='dataType_dict',
            field=models.TextField(blank=True, default='{"headers":[], "body":[], "validate":[], "variables":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='description_dict',
            field=models.TextField(blank=True, default='{"headers":[], "body":[], "validate":[], "variables":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='extract',
            field=models.TextField(blank=True, default='[ ]'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='headers',
            field=models.TextField(blank=True, default='{ }'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='necessaryFlag_dict',
            field=models.TextField(blank=True, default='{"headers":[], "body":[], "variables":[]}'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='setup_hooks',
            field=models.CharField(blank=True, default='[]', max_length=200),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='skip',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='skipIf',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='skipUnless',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='teardown_hooks',
            field=models.CharField(blank=True, default='[]', max_length=200),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='validate',
            field=models.TextField(blank=True, default='[ ]'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='variables',
            field=models.TextField(blank=True, default='[ ]'),
        ),
    ]
