# Generated by Django 2.0.1 on 2018-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0022_auto_20181217_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
