# Generated by Django 2.0.1 on 2018-12-18 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0023_testcases_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 10, 21, 23, 858400)),
        ),
    ]
