# Generated by Django 2.0.1 on 2018-12-24 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0024_auto_20181218_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 10, 21, 28, 979000)),
        ),
    ]
