# Generated by Django 2.0.1 on 2018-12-24 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0025_auto_20181224_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
