# Generated by Django 2.0.1 on 2019-01-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0027_auto_20190110_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='mock_status',
            field=models.CharField(blank=True, default='1', max_length=2),
        ),
    ]
