# Generated by Django 2.0.1 on 2019-01-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0028_auto_20190111_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockserver',
            old_name='status',
            new_name='mock_status',
        ),
    ]
