# Generated by Django 2.0.1 on 2019-02-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoTest', '0029_auto_20190111_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('func_id', models.AutoField(primary_key=True, serialize=False)),
                ('func_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='run_stat',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
